### ISSUE TITLE
How can i install multiple servers?

### ISSUE THREAD

**Issue by sagnol** [Khezen/docker-mongo-rocks#17]
First of all, Thank you for making docker image to easily install.  
I am trying to install mongo shard multiple servers with your docker image.  

But, 

mongos cannot find shard nodes in another machines. (separated mongos & shard nodes)

```
mongos:  
    image: khezen/mongo:3.4  
    container_name: mongos  
    environment:  
      CONFIG_SERVERS: configsvr/configsvr1:27017  
      SHARDS: shard1/192.168.0.x:port shard2/192.168.0.x:port 
      STORAGE_ENGINE: wiredTiger  
```
in another machine
```
shard1_replica1:
    image: khezen/mongo:3.4
    container_name: s1-n1
    environment:
      RS_NAME: shard1
      SHARD_SVR: 'y'
      MASTER: shard1_replica1
      STORAGE_ENGINE: wiredTiger
    volumes:
      - ./data/mongo/shard1/replica1:/data/db
    ports:
      - "27011:27017"
    restart: always
```

Please let me know solution.

Thank you.
