### ISSUE TITLE
mongod doesn't execute and gives illegal instruction $cmd

### ISSUE THREAD

**Issue by BelalAmin** [Khezen/docker-mongo-rocks#19]
this is the content of my docker-compose.yml
`
```
version: '3'
services:
 mongodb:
   image: khezen/mongo3.4
   ports:
     - "27018:27017"
   volumes:
     - ./mongo-datadir:/data/db
```
`
when I docker-compose up on both of my local machines which are ubuntu 14.04 and ubuntu 16.4 it works fine, however, when I tried to get it to work on my Linode server it ran into an infinite loop in the 
and gives the following output 
![mongo_issue](https://user-images.githubusercontent.com/6377873/29502411-8c484642-8638-11e7-89de-28adc5c9f5e1.png)
I have tried every thing I can, I have no idea what is happening, why it gives illegal instruction $cmd. 
I will be very glad if someone can help, thanks in advance
